services:
#  app:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - SEED_DATABASE=true
#    volumes:
#      - ./appsettings.json:/app/appsettings.json
#    depends_on:
#      - db
#    build:
#      context: .
#    ports:
#      - "5000:80"
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      SA_PASSWORD: "D3vP@ss!8"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - db-data-order-management:/var/opt/mssql/data
    ports:
      - "1433:1433"

volumes:
  db-data-order-management:      